config/routes.rb
Rails.application.routes.draw do
  resources :links
  root  'links#index'
  
  get ':short_url' => 'links#redirect'
  match 'shorten', to: 'links#create', via: :post
 

end

app/models/concerns/url_validator.rb
class UrlValidator < ActiveModel::EachValidator

  def validate_each(record, attribute, value)
    valid = begin
      URI.parse(value).kind_of?(URI::HTTP)
    rescue URI::InvalidURIError
      false
    end

    unless valid
      record.errors[attribute] << (options[:message] || "is not a valid URL")
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base

  before_validation :generate_short_url, except: [:update]
  validates :full_url, presence: true, url: true, allow_blank: false
  validates :short_url, presence: true, uniqueness: true

  private

  # Generate a unique short_url for a given web address
  def generate_short_url
    url = Process.clock_gettime(Process::CLOCK_REALTIME, :nanosecond).to_s(36)
    old_url = Link.where(short_url: url).last
    if old_url.present? 
      self.generate_short_url
    else
      self.short_url = url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def redirect
    @link = Link.find_by(short_url: params[:short_url])
    respond_to do |format|
      if @link && @link.update(access_count: @link.access_count + 1)
        format.html { redirect_to @link.full_url, status: 301 }
        format.js {}
      else 
        format.html { redirect_to root_url, notice: "URL not found. Please try again or generate a new URL" }
        format.js {}
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Permit full_url alone.
    def link_params
      params.require(:link).permit(:full_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def base_url(short_url = nil)
    "#{request.protocol}#{request.host_with_port}/#{short_url}"
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_url %><br>
    <%= f.text_field :full_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Links</h1>

<table border="1">
  <thead>
    <tr>
      <th>Full url</th>
      <th>Short url</th>
      <th>Access count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link_to link.full_url, link.full_url, target: "_blank" %></td>
        <td><%= link_to base_url(link.short_url), base_url(link.short_url), target: "_blank" %></td>
        <td><%= link.access_count %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full url:</strong>
  <%= @link.full_url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= base_url(@link.short_url) %>
</p>

<p>
  <strong>Access count:</strong>
  <%= @link.access_count %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>